# Generated by Django 3.0.7 on 2020-07-08 18:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0011_auto_20200702_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='title tag', max_length=255),
        ),
    ]
